# Generated by Django 5.1.2 on 2024-11-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('experience_level', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_resume', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.jobpreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.user')),
            ],
        ),
        migrations.AddField(
            model_name='jobpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.user'),
        ),
    ]
